project_id = "mhbhzbgxyjqkokilxpfw"

[functions.create-checkout]
verify_jwt = false

[functions.create-manual-order]
verify_jwt = false

[auth]
# Leaked password protection (HIBP)
# Ces cl√©s sont invalides dans cette version de la CLI
# pwned_password_protection_enabled = true
# enable_pwned_passwords = true
