project_id = "andemnvsudxiraosokwd"

[functions.create-checkout]
verify_jwt = false

[functions.create-manual-order]
verify_jwt = false

[auth]
# Leaked password protection (HIBP)
pwned_password_protection_enabled = true
enable_pwned_passwords = true